version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:80"
    depends_on:
      - db

  redis:
    image: redis:alpine3.22
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:latest
    ports:
      - "${PR_PORT}:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  grafana:
    container_name: grafana
    image: grafana/grafana:main-ubuntu
    environment:
      GF_SECURITY_ADMIN_USER: ${GR_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GR_PASSWORD}
    ports:
      - "${GR_PORT}:3000"
    depends_on:
      prometheus:
        condition: service_started
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  springapp:
    build:
      context: ../../app/comp_store
      dockerfile: Dockerfile
    container_name: spring_app
    ports:
      - "${SPRING_PORT}:8080"
    depends_on:
      grafana:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: prod

volumes:
  pg_data:
  redis_data:
  grafana_data:
